### ISSUE TITLE
Add "/setMaintenance" methods

### ISSUE THREAD

**Issue by kamaev** [moira-alert/python-moira-client#8]

**Comment by idoqo** [comment]
Hi @beevee, I'm trying to get familiar the library as part of the OpenAPI description project.

I was wondering if `/setMaintenance` method here should work in same way turning off this switcher on the `/notifications` page in web.
<img width="225" alt="75016271-a7cb3d00-549b-11ea-8834-af66a257bdd8" src="https://user-images.githubusercontent.com/10512379/75684120-7c650100-5c98-11ea-8eb0-14dee006b448.png">

**Comment by beevee** [comment]
> I was wondering if `/setMaintenance` method here should work in same way turning off this switcher on the `/notifications` page in web.

No, it should not. These methods are for metric maintenance:
![image](https://user-images.githubusercontent.com/1009675/75747173-0b782480-5d3e-11ea-8c3d-c84ae0269162.png)

**Comment by idoqo** [comment]
Alright, got it now. Thanks a lot.
